index:
  path: /
  controller: App\Controller\IndexController::index

course:
  path: cursussen/
  controller: App\Controller\PageController::course

course_info:
  path: cursus-info/
  controller: App\Controller\PageController::courseInfo

boats:
  path: boten/
  controller: App\Controller\PageController::boats

contact:
  path: contact/
  controller: App\Controller\PageController::contact

signin:
  path: signin/
  controller: App\Controller\PageController::signin

admin:
  path: admin/
  controller: App\Controller\PageController::admin



