index:
  path: /
  controller: App\Controller\IndexController::index

course:
  path: cursussen/
  controller: App\Controller\PageController::course

boats:
  path: boten/
  controller: App\Controller\PageController::boats

contact:
  path: contact/
  controller: App\Controller\FormController::contact

sign_in:
  path: aanmelden/
  controller: App\Controller\FormController::signIn

